config/routes.rb
Rails.application.routes.draw do

  resources :locations

  get 'maps/map'

  devise_for :users

	resources :answers, only: :index

  root 'home#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	def index
    @name = "Sherri Mitchell"
    @email = "rsamitchell@att.net"
    @github = "https://github.com/sherrimitchell"
    @linkedin = "https://www.linkedin.com/in/sherri-mitchell-669285b"
    @fork = "Cloning a repository allows a user to create a local copy of a repository on their machine and sync their work between the two. Forking a repository allows a user to contribute to a project by pushing to the repository and creating a pull request. By forking the Standard Code repository, I am able to push my work to back up and it can then be reviewed."
    @oneMorething = "This scavenger hunt has been both interesting and challenging. I was both excited and anxious to tackle the maps portion. I thought that it would be something that I would have some challenges with, but would ultimately be able to do in a reasonable amount of time. Come Friday, the last day for submission, I was finally able to get it completed. After getting the map and points to render, I realized that the most difficult part of this exercise was me getting over myself. A combination of fear and stubborness compelled me to go in a direction that was not the best choice. It took much more time and effort than it should have. I had to finally stop and realize that the track I was on was wrong. Wrong for many reasons, but most of all it was not what was needed for this project. I chose a path that was not getting me to the goal. I had to shift my thinking, start over a couple of times, and learn my lesson. I guess ultimately I am saying that this was so much freakin' fun! Thanks for the opportunity."
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
    @hash  = Gmaps4rails.build_markers @locations do |location, marker|
      marker.lat location.latitude
      marker.lng location.longitude
    end

    # respond_to do |format|
    #   format.html { render :index }
    #   format.json { render json: @locations }
    # end    
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:lat, :lng, :distance, :bearing)
    end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def index
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def map
  	@locations = Location.all
    @hash  = Gmaps4rails.build_markers @locations do |location, marker|
      marker.lat location.latitude
      marker.lng location.longitude
    end

    # puts @hash
  end
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  def index
   	  marker_locations = Location.all
	  render :json => marker_locations
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_field :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<div class="home">
	<h1>FAQs</h1>
  <p>Never one to leave an audience waiting in suspense, see below to find out what all the fuss is about:</p>
  <ol>
    <ul>
      <p><b>What is your name?</b></p>
      <p><%= @name %></p>
      <p><b>What is your email address?</b></p>
      <p>My email address is: <%= @email%>. </p>
      <p><b>What is my Github url?</b></p>
      <p>Here is the link to <a href="<%= @github %>">my repository on Github</a>.</p>
      <p><b>What is your Linkedin url?</b></p>
      <p>Here is <a href="<%= @linkedin %>">where I live on Linkedin</a>.</p>
      <p><b>Can you tell us why we asked you to fork this repo instead of clone it?</b></p>
      <p><%= @fork %></p>
      <p><b>Tell us about your favorite coding project of all time? What was great about it?</b></p>
      <p>My favorite coding project of all time is my Blogger app. Back in June, I began doing some video tutorials for Ruby on Rails. I was on a mission to really solidify some fundamentals for myself. I felt as if I was doing some things purely by rote, and I wanted a way to really put things together for me. Writing things down helps me retain concepts. I decided that I was going to watch a tutorial, and as I made my way through I would pause and write down everything. I made sure that I wrote down the code before I entered it in the editor. I found some instructional videos by a blogger named Mackenzie Childs, and the first project that I chose to do was Blogger. Even though I had done this same project during my boot camp days, I was not confident that I really understood it well enough to replicate it on my own. So, I went through the tutorial writing down each step and carefully following in the editor. By the end of the exercise, I felt so much more confident in my understanding. I then replicated the entire project myself without the video. That was a turning point for me and helped me feel so much more confident in myself. Although Blogger is a staple for beginners that is not fancy or sparkly, it really is a great project for learning fundamentals of rails.</p>
      <p><b>One More Thing</b></p>
      <p><%= @oneMorething %></p>
    </ul>
  </ol>
</div>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p>
  <strong>Question:</strong>
  <%= @answer.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @answer.answer %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/home/index.html.erb
maps<div class="home">
	<div class="sherri-info">
		<h1>Sherri Mitchell</h1>
    <p>Hi! I'm Sherri and I am a software engineer. This may seem like a simple phrase, but for me it represents a special part of a journey that I began a long time ago. Over a year and a half ago, I was well into my career as a technical business analyst and I decided to change careers. I had always wanted to be a developer, but I kept that dream tucked safely away waiting for that point in time where all the stars would align and I would have the freedom to pursue it. One day I realized that there really is no perfect time, and that the present was as perfect as it gets. I took a leap of faith in myself and began to do self-study, and then eventually graduated from a boot camp back-end engineering program. Since my graduation, I have continued to learn on my own, volunteer, and attend meetups. This summer I was fortunate to have been chosen as an intern for the Rails Girls Summer of Code. Since July, my team mate and I have been working on an open source project called Open Source Event Management System (OSEM) <a href="https://github.com/openSUSE/osem">here is a link to the repository on Github</a>. <a href="https://github.com/openSUSE/osem">OSEM</a> is <i>an event management tool tailored to Free and Open Source Software conferences</i>. The project code base is much bigger than any I had ever worked on, and I remember being extremely intimidated when we started. I thought to myself that I had taken on too much, and there was no way that I could be successful since I didn't know everything about coding. At some point during this process, I realized that I didn't need to know everything about coding. No one does. In fact, the magic (and the fun) is in not knowing and being on the quest to find out.</p>
    <p>I saw a statistic that says 80% of people aged 45 and over consider changing their careers, but only 6% actually do. I wish that I could tell the other 74% how great it is on the other side! I love what I do, and I look forward to my future in the industry.</p>
    <p>Besides coding, I also love to spend time with my family, play tennis, fix various appliances around my house, and do things to try and use up the copious amounts of glue, cloth, wood, etc. that seem to find their way into my 'craft room'.</p>

    <p>If you'd like to learn a few more fun facts about me you can go here <%= link_to "FAQs", answers_path %>.</p>
	</div>
	<p><%= link_to "Map", maps_map_path %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Apprentice</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body>

  <svg class="logo" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Layer_1" x="0px" y="0px" viewBox="0 0 1000 1000" enable-background="new 0 0 1000 1000" xml:space="preserve">
  <g>
    <path fill="#ffffff" d="M703,963.7H297c-29.3,0-56.2-16-70.1-41.8L19.8,537.8c-12.8-23.7-12.8-51.9,0-75.6L227,78.1   c13.9-25.8,40.8-41.8,70.1-41.8H703c29.3,0,56.2,16,70.1,41.8l207.2,384.1c12.8,23.7,12.8,51.9,0,75.6L773,921.9   C759.1,947.7,732.3,963.7,703,963.7z M297,49.3c-24.5,0-47,13.4-58.6,35L31.3,468.4c-10.7,19.8-10.7,43.4,0,63.2l207.2,384.1   c11.6,21.6,34.1,35,58.6,35H703c24.5,0,47-13.4,58.6-35l207.2-384.1c10.7-19.8,10.7-43.4,0-63.2L761.6,84.3   c-11.6-21.6-34.1-35-58.6-35H297z"/>
    <g>
      <polygon fill="#ffffff" points="501.3,832.8 510.7,851.9 531.7,854.9 516.5,869.8 520.1,890.7 501.3,880.8 482.4,890.7 486,869.8     470.8,854.9 491.8,851.9   "/>
      <polygon fill="#ffffff" points="339.2,832.8 348.6,851.9 369.6,854.9 354.4,869.8 358,890.7 339.2,880.8 320.4,890.7 324,869.8     308.8,854.9 329.8,851.9   "/>
      <polygon fill="#ffffff" points="663.3,832.8 672.7,851.9 693.7,854.9 678.5,869.8 682.1,890.7 663.3,880.8 644.5,890.7     648.1,869.8 632.9,854.9 653.9,851.9   "/>
    </g>
    <g>
      <g>
        <path fill="#ffffff" d="M433.9,632.3c-19,0-33.4-6.5-43-19.4c-8.3-11.2-12.6-26.8-12.6-46.2v-15.2h13.6v15.6     c0,23.6,7.3,51.7,42,51.7c19.2,0,42-9,42-51.7c0-29.6-22-44.3-45.3-59.8c-25.1-16.8-51.1-34.1-51.1-71.2     c0-41.7,19.5-64.9,54.8-65.3c19,0,33.4,6.6,42.9,19.6c8.2,11.2,12.4,26.7,12.4,46v7.7h-13.9v-8c0-43-22.3-52.1-40.9-52.1     c-18.8,0-41.3,9-41.3,51.7c0,30.1,22.3,45,45.8,60.8c24.9,16.7,50.7,33.9,50.7,70.2c0,19.4-4.2,35-12.6,46.2     C467.6,625.8,453,632.3,433.9,632.3z"/>
      </g>
      <g>
        <path fill="#ffffff" d="M567.1,632.3c-35.3,0-55.6-24.3-55.6-66.7V437.5c0-42.4,20.3-66.7,55.6-66.7c35.5,0,55.9,24.3,55.9,66.7     v22.4h-13.9v-22.8c0-43.9-22.6-53.2-41.6-53.2c-19.2,0-42,9.2-42,53.2V566c0,24.1,7.3,52.8,42,52.8c34.4,0,41.6-28.7,41.6-52.8     v-30.7H623v30.4C623,608,602.6,632.3,567.1,632.3z"/>
      </g>
    </g>
  </g>
  </svg>

  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert"><%= alert %></p>
  <% end %>
  <%= yield %>
  <%= yield :scripts %>
  <%= render 'layouts/google_analytics' %>
</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.text_field :lng %>
  </div>
  <div class="field">
    <%= f.label :distance %><br>
    <%= f.text_field :distance %>
  </div>
  <div class="field">
    <%= f.label :bearing %><br>
    <%= f.text_field :bearing %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<div id="container-fluid">
  <div id="map-container">	
    <div id="map-canvas" ><%= javascript_include_tag 'maps' %></div>
  </div>
</div>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lat:</strong>
  <%= @location.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @location.lng %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @location.distance %>
</p>

<p>
  <strong>Bearing:</strong>
  <%= @location.bearing %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/map/index.html.erb
<h1>Apprentice Map</h1>
<section>
  <figure class="map-container col-xs-11" style="height: 400px;">
    <div id="map" style="height: 100%;"></div>
  </figure>
</section>
<script>
  var map;
  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
        center: {lat: 33.45115165, lng: -84.47746155},
        zoom: 8
    });
    var markersArray = []
    function makeMarkers(locations){
      locations.forEach(function(location){
        location.lat = Number(location.lat);
        location.lng = Number(location.lng);
        markersArray.push(location);
      });
    }
    $.ajax({
      url: "http://localhost:3000/markers",
      dataType: 'json'
    }).then(function(locations){
      makeMarkers(locations);
      markersArray.forEach(function(location, index){
        var marker = new google.maps.Marker({
          position: {lat: location.lat, lng: location.lng},
          map: map,
          title: 'Marker'
        });
      })
    });
  }    
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDcIecppzG4vbgx-iT0f4YhbiRNr4J2dKM&callback=initMap"async defer></script>

app/views/maps/map.html.erb
<script type="text/javascript" src="//maps.google.com/maps/api/js?key=AIzaSyCNkT70Bt9dK-Xwa_4ZyqnJRADzn7DBg0U"></script>
<script type="text/javascript" src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<%= javascript_include_tag "underscore", "data-turbolinks-track" => "reload" %>

<div id="container-fluid">
  <div id="map-container">	
    <div id="map" ><%= javascript_include_tag 'maps' %></div>
  </div>
</div>

 <script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {
  	zoom: 8
  }, 
  	internal: {
  		id: 'map'
  	}}, 
  	function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>